sonar.projectKey=ifs24056-pabwe2026-sk-p5-nuxt
sonar.projectName=ifs24056-pabwe2026-sk-p5-nuxt

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.js,**/*.test.tsx,**/*.test.jsx

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**,dist/**,.output/**,.nuxt/**,src/setupTests.ts,src/test-utils.ts,src/main.ts,src/**/*.d.ts,**/*.test.ts,**/*.test.js,**/*.test.tsx,**/*.test.jsx